name: e_store_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.16.1
  another_flushbar: ^1.12.30
  google_fonts: ^6.1.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner.png
